name: CI

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.0"
          - "8.1"
          - "8.2"
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }}
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php }}
    - uses: php-actions/phpstan@v3
      with:
        php_version: ${{ matrix.php }}
        path: src/
    - run: composer test
    - run: bash <(curl -s https://codecov.io/bash)
